version: '3.8'
services:
  otomar:
    container_name: otomar
    image: postgres
    restart: always
    ports:
      - 2222:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: otomar
    volumes:
      - C:\develop\projects\BudgetManagement\Docker\init.sql:/docker-entrypoint-initdb.d/init.sql
